name: joblance
description: "Jobs and  freelancing  portal"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_animated: ^3.2.0
  chips_choice: ^3.0.1
  dartz: ^0.10.1
  flutter_animate: ^4.2.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  image_picker: ^1.0.4
  lottie: ^2.6.0
  path: ^1.8.3
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  show_up_animation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
  fonts:
      - family: Cairo
        fonts:
          - asset: assets/fonts/Cairo_Bold.ttf
            weight: 700
      - family: Trajan Pro
        fonts:
          - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          - asset: assets/fonts/PlayfairDisplay-Regular.ttf
            weight: 700 