name: joblance
description: "Jobs and  freelancing  portal"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_animated: ^3.2.0
  carousel_slider: ^4.2.1
  chips_choice: ^3.0.1
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  date_picker_plus: ^2.1.0
  emoji_picker_flutter: ^1.6.3
  file_picker: ^6.2.0
  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  http: ^0.13.6
  image_picker: ^1.0.4
  lottie: ^2.6.0
  path: ^1.8.3
  shared_preferences: ^2.2.1
  flutter_speed_dial: ^7.0.0
  shimmer: ^3.0.0
  show_up_animation: ^2.0.0
  flutter_paypal_checkout: ^1.0.1
  jiffy: ^6.2.2
  flutter_file_downloader: ^2.0.0
  url_launcher: ^6.2.6
  popover: ^0.2.9
  flutter_rating_bar: ^4.0.1
  flutter_sound: 9.2.13
  soundpool: ^2.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#000000"
  image: "assets/images/splash.png"
  icon_background_color: "#363636"
  android_12: 
    image: "assets/images/splash.png"
    color: "#000000"
    icon_background_color: "#363636"
    

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo3.png"
  adaptive_icon_background: "#363636"
  min_sdk_android: 21
  flutter_lints: ^3.0.0

  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo_Bold.ttf
          weight: 700
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 700
