Map<String, String> arabic = {
  "title1": "",
  "title2": "",
  "title3": "",
  "title4": "",
  "body1": "",
  "body2": "",
  "body3": "",
  "body4": "",
  "body5": "",
  "continuebutton": "التالي",
  "chooselanguage": "إختر لغتك المفضلة",
  "login": "تسجيل الدخول",
  "skipbutton": "تخطي",
  "english": "الإنجليزية",
  "arabic": "العربية",
  "signup": "إنشاء حساب",
  "createaccount": "ليس لديك حساب ؟",
  "location": "الموقع",
  "settings": "الإعدادات",
  "profile": "الملف الشخصي",
  "firstname1": "أدخل الاسم الأول",
  "firstname2": "الاسم الأول",
  "password2": "كلمة السر",
  "password1": "أدخل كلمة المرور",
  "signupbody": "أنشىء حسابك الآن للبدء",
  "lastname1": "أدخل الكنية",
  "laststname2": "الكنية",
  "phone2": "رقمك",
  "phone1": "أدخل رقمك",
  "email2": "البريد الإلكتروني",
  "email1": "أدخل البريد الإلكتروني",
  "homepage": "الرئيسية",
  "search": "ابحث",
  "favorite": "المفضلة",
  "categories": "الفئات",
  "additional": "معلومات إضافية",
  "welcome": "أهلا بك",
  "alreadyhaveaccount": "لديك حساب بالفعل ؟",
  "logintocontinue": "سجل دخولك للإكمال",
  "confirmpassword1": "أعد إدخال كلمة المرور",
  "confirmpassword2": "كلمة المرور",
  "myaccount": "حسابي الشخصي",
  "changelanguage": "تغيير اللغة",
  "darkmode": "الوضع الداكن",
  "logout": "تسجيل الخروج",
  "offices": "مكاتب",
  "lightmode": "الوضع الساطع",
  "choosemode": "اختر الوضع",
  "filter": "فلتر البحث",
  "confirm": "تأكيد",
  "warningbody": "هل تريد الخروج من التطبيق؟",
  "yes": "نعم",
  "no": "لا",
  "myfavorite": "المفضلة",
  "continuewithgoogle": "التسجيل عن طريق غوغل",
  "addyourinfo": "أدخل معلوماتك",
  "companyname1": "اسم الشركة",
  "companyname2": "أدخل اسم الشركة",
  "chooseyourcountry": "اختر مكان إقامتك",
  "numofemployees": "عدد الموظفين",
  "major": "الإختصاص",
  "company": "شركة",
  "freelancer": "مستقل",
  "recentjobs": "أضيفت مؤخرا",
  "relatedtoyou": "متعلقة باختصاصك",
  "notifications": "الإشعارات",
  "hello": "مرحبا",
  "active": "مفعلة",
  "inactive": "متوقفة",
  "applay": "تقدم",
  "aboutcompany": "عن الشركة:",
  "aboutjob": "عن العمل:",
  "requirments": "المتطلبات:",
  "remote": "عن بعد",
  "hybrid": "مختلط",
  "onsite": "مكتبي",
  "fulltime": "دوام كامل",
  "parttime": "دوام جزئي",
  "internship": "تدريب",
  "applicants": "متقدم ",
  "junior": "مبتدئ",
  "senior": "متقدم",
  "temporary": "مؤقت",
  "director": "مدير",
  "popularjobs": "وظائف شائعة",
  "general": "عام",
  "account": "الحساب الشخصي",
  "helpcenter": "مركز الدعم",
  "appmode": "الوضع الداكن",
  "applaiedjobs": "الوظائف المقدم عليها",
  "report": "إبلاغ",
  "abouttheapp": "عن التطبيق",
  "language": "اللغة",
  "follow": "متابعة",
  "suggestedjobs": "وظائف مقترحة",
  "messages": "الرسائل",
  "aboutcompany2": "أدخل تعريف مختصر عن شركتك",
  "reporttitle": "عنوان المشكلة",
  "reportdescription": "شرح المشكلة",
  "showmore": "عرض المزيد",
  "send": "إرسال",
  "employees": "الموظفين",
  "studycase": "الوضع الدراسي",
  "savedjobs": "الوظائف المحفوظة",
  "applayforthejob": "التقدم للعمل",
  "uploadyourcv": "أضف السيرة الذاتية",
  "coverletter": "رسالة حافز",
  "optional": "(اختياري)",
  "additionalinfo": "معلومات إضافية:",
  "editprofile": "تعديل الحساب",
  "yourreporthasbeensent": "تم إرسال الإبلاغ بنجاح",
  "sendingyourreport": "جاري إرسال الإبلاغ",
  "yourrequesthasbeensent": "تم إرسال طلبك",
  "message": "رسالة",
  "popularfreelancers": "أبرز المستقلين",
  "verifyingcode": "التحقق من البريد الالكتروني",
  "receivedcode": "أدخل الكود الذي استلمته",
  "youbirthdate": "أدخل تاريخ ميلادك",
  "bio2": "أدخل موجز عن نفسك",
  "birthdate": "تاريخ الميلاد",
  "errorsendingyourrequest": "لم يتم إرسال طلبك بنجاح",
  "changepassword": "تغيير كلمة المرور",
  "oldpassword1": "أدخل كلمة المرور الحالية",
  "oldpassword2": "كلمة المرور الحالية",
  "newpassword1": "أدخل كلمة المرور الجديدة",
  "newpassword2": "كلمة المرور الجديدة",
  "confirmnewpassword1": "تأكيد كلمة المرور",
  "confirmnewpassword2": "أعد إدخال كلمةالمرور",
  "resendthecode": "أعادة إرسال الرمز بعد ",
  "resend": "أعادةإرسال",
  "forgotyourpassword": "هل نسيت كلمة السر؟",
  "enteremail": "أدخل البريد الالكتروني لإرسال رمز التحقق",
  "resetyourpassword": "إعادة تعيين كلمو المرور",
  "emailverified": "تم التحقق",
  "enternewpassword": "أدخل كلمة المرور الجديدة",
  "reset": "أعادة تعيين",
  "sendingcodetoemail": "إرسال رمز التفعيل",
  "passworddoesntmatch": "كلمة المرور غير مطابقة",
  "pleaseaddanimage": "الرجاء إضافة صورة",
  "about": "حول",
  "savechanges": "حفظ التغييرات",
  "jobs": "فرص عمل",
  "contact": "تواصل",
  "interests": "اهتمامات",
  "projects": "مشاريع",
  "products": "منتجات",
  "checkingcode": "التحقق من الرمز",
  "wrongcode": "رمز خطأ",
  "empty": "لا يمكن أن يكون فارغ",
  "warningbody2": "البريد الالكتروني أو رقم الهاتف موجود بالفعل",
  "less": "لايمكن أن يكون أقل من ",
  "more": "لا يمكن أن يكون أكثر من ",
  "letters": "أحرف",
  "opentowork": "جاهز للعمل",
  "pickupyourcounntry": "أختر بلدك",
  "errorloggingin": "حصل خطأ أثناء التسجيل",
  "wrongoldpassword": "كلمة المرور القديمة خاطئة",
  "passwordchangedsucessfully": "تم تغيير كلمة المرور بنجاح",
  "processingyourrequest": "جاري معالجة طلبك",
  "completeyourinfo": "أكمل معلوماتك",
  "existednumber": "رقم الهاتف موجود بالفعل",
  "aboutjob2": "اشرح وظيفة العمل",
  "jobtitle": "عنوان العمل",
  "jobtitle2": "",
  "requirements": "المتطلبات",
  "requirements2": "أدخل متطلبات العمل",
  "jobtype": "نوع العمل",
  "jobexperince": "الخبرة المطلوبة",
  "companyinfo": "معلومات الشركة",
  "shownumofemployees": "إظهار عدد موظفي الشركة",
  "showaboutcompany": "إظهار معلومات الشركة",
  "fillyourjobinfo": "إملئ معلومات العمل",
  "post": "نشر",
  "additionalinfo2": "(اختياري)",
  "jobadditionalinfo": "معلومات إضافية",
  "aboutjob1": "وصف العمل",
  "joblocation": "مكان العمل",
  "companyproducts": "منتجات الشركة",
  "contactinfo": "معلومات التواصل",
  "joblocation2": "أدخل مكان العمل",
  "bio": "معلومات شخصية",
  "producttitle": "اسم المنتج",
  "projecttitle": "اسم المشروع",
  "productdescription": "وصف المنتج",
  "projectdescription": "وصف المشروع",
  "projectdescription2": "أضف وصف لمشروعك",
  "productdescription2": "أضف وصف لمنتجك",
  "producttitle2": "أدخل اسم المنتج",
  "projecttitle2": "أدخل اسم المشروع",
  "link": "الرابط",
  "addyourlink": "أضف رابط",
  "addimage": "أضف صورة",
  "addyourproduct": "أضف منتجك",
  "addyourproject": "أضف مشروعك",
  "skills": "المهارات",
  "yourpasswordhasbeenchanged": "تم تغيير كلمة المرور",
  "projectlink": "رابط المشروع",
  "gender": "الجنس",
  "male": "ذكر",
  "female": "أنثى",
  "projectimages": "صور عن المشروع",
  "wronglogin": "خطأ في البريد الإلكتروني أو كلمة المرور",
  "youremailhasbeenverified": "تم تأكيد بريدك الإلكتروني",
  "emailisnotexisted": "البريد الإلكتروني غير موجود",
  "youremailisnotverified": "البريد الإلكتروني غير مؤكد\nهل تريد تأكيده؟",
  "checkingdata": "تتم معالجة طلبك",
  "lastweek": "الأسبوع الماضي",
  "lastmonth": "الشهر الماضي",
  "dateposted": "وقت النشر",
  "addproject": "أضف مشروع",
  "addyourskill": "أضف مهارتك",
  "addskill": "أضف مهارة",
  "myjobs": "وظائفي",
  "cantaddmorethan6images": "لا يمكن إضافة أكثر من 6 صور",
  "addtask": "إملاء معلومات المهمة",
  "tasktitle": "عنوان المهمة",
  "tasklocation": "",
  "tasktitle2": "أدخل عنوان المهمة",
  "tasklocation2": "",
  "abouttask1": "معلومات المهمة",
  "abouttask2": "اشرح معلومات المهمة",
  "taskadditionalinfo": "المهلومات الإضافية",
  "taskduration": "مدة المهمة",
  "taskduration2": "أدخل مدة المهمة",
  "days": "أيام",
  "add": "إضافة",
  "offers": "العروض",
  "budget": "قيمة المهمة",
  "task": "مهمة",
  "job": "وظيفة",
  "pleasewait": "الرجاء الإنتظار",
  "studyinfo": "معلومات الدراسة",
  "mytasks": "مهامي",
  "tasks": "المهمات",
  "showall": "عرض الكل",
  "addoffer": "إضافة عرض",
  "abouttask": "معلومات المهمة",
  "excutingtime": "وقت التنفيذ",
  "offerbudget": "قيمة العرض",
  "offerinfo": "معلومات العرض",
  "mybudget": "محفظتي",
  "min": "أقل قيمة",
  "max": "أعلى قيمة",
  "withdraw": "سحب:",
  "deposit": "إيداع:",
  "on": "في",
  "value": "القيمة",
  "lasttransmissions": "اخر التحويلات",
  "title": "العنوان",
  "description": "الوصف",
  "images": "الصور",
  "couldn'tdelete": "لم تنجح عملية الحذف",
  "doyoureallywanttodelete": "هل تريد حقا الحذف؟",
  "errorwhilesavingdata": "حدث خطأ أثناء الحفظ",
  "couldn'tloadinfo": "لم يتم تحميل المعلومات",
  "doyoureallywanttodeletetheskill":"هل تريد حقا حذف المهارة؟",
  "couldn'tdeleteyourskill":"لم يتم حذف المهارة",
  "couldn'topenlink":"هناك خطأ في الرابط",
  "addproduct":"إضافة منتج",
  "expectedsalary":"الراتب المتوقع",
  "yearsofexperience":"سنوات الخبرة",
  "fillyourofferinformation":"قم بإضافة معلوماتك للتقدم للعمل",
  "yourproducthasbeenadded":"تم إضافة المنتج بنجاح","yourprojecthasbeenadded":"تم إضافة المشروع بنجاح",
  "showinimportantjobs":"إظهار في قائمة الفرص المهمة",
  "nointernetconnection":"لايوجد اتصال بالانترنت","servererror":"خطأ في تحميل البيانات",
  "thisallowsyoutoaddyourjobtoimportantjobsitcoastsonly5":"يقوم هذا الخيار بإضافة فرصة العمل إلى قائمة الفرص المهمة\ىيكلف فقط 5\$"
};
