Map<String, String> english = {
  "title1": "Welcome to Joblance",
  "title2": "Find your dream job and\nbuild your carrer ",
  "title3": "Easy communication",
  "title4": "Jobs accoarding to your major",
  "body1": "Join as a freelancer or as\ncompany and make your dreams real",
  "body2": "Explore thousands of great jobs\n or add your job chance ",
  "body3":
      "Connect easly between company and\nthe freelancer through messaging",
  "body4": "Explore suggested jobs accoarding\n to your major or search",
  "body5": "",
  "continuebutton": "Continue",
  "chooselanguage": "Choose your language",
  "skipbutton": "Skip",
  "english": "English",
  "arabic": "Arabic",
  "welcome": "Welcome to Sstate",
  "login": "Login",
  "signup": "Sign Up",
  "bio": "Bio",
  "bio2": "Enter a brief explanation about yourself",
  "createaccount": "Don't have an account ?",
  "search": "Search",
  "homepage": "Home",
  "settings": "Settings",
  "profile": "Profile",
  "favorite": "Favorite",
  "location": "Location",
  "categories": "Categories",
  "addinfo": "Add your info to continue",
  "alreadyhaveaccount": "Already have an account ?",
  "logintocontinue": "Login to continue",
  "firstname2": "First name",
  "firstname1": "",
  "password2": "Password",
  "password1": "Enter your password",
  "lastname1": "",
  "lastname2": "Last name",
  "phone1": "Enter your Phone",
  "phone2": "Phone",
  "email1": "Enter your email",
  "email2": "Email",
  "confirmpassword1": "Confirm your password",
  "confirmpassword2": "Password",
  "myaccount": "My Account",
  "changelanguage": "Change language",
  "darkmode": "Dark Mode",
  "logout": "Logout",
  "choosemode": "Choose mode",
  "filter": "Filter",
  "confirm": "Confirm",
  "warningbody": "Are you sure you want to exit?",
  "yes": "Yes",
  "no": "No",
  "myfavorite": "My Favorite",
  "continuewithgoogle": "Continue with google",
  "deletingapointment": "Do you want to cancel this appointment?",
  "addyourinfo": "Add your information",
  "companyname2": "Company name",
  "companyname1": "Enter your company name",
  "chooseyourcountry": "Choose your country",
  "numofemployees": "Num of employees",
  "major": "Major",
  "company": "Company",
  "freelancer": "Freelancer",
  "recentjobs": "Recent jobs",
  "relatedtoyou": "Related jobs",
  "notifications": "Notifications",
  "hello": "Hello",
  "active": "Active",
  "inactive": "In active",
  "applay": "Apply",
  "aboutcompany": "About Company:",
  "aboutjob": "About job:",
  "requirments": "Requirments:",
  "remote": "Remote",
  "hybrid": "Hybrid",
  "onsite": "On-Site",
  "fulltime": "Full time",
  "parttime": "Part time",
  "internship": "Internship",
  "applicants": " Applicants",
  "junior": "Junior",
  "senior": "Senior",
  "temporary": "Temporary",
  "director": "Director",
  "popularjobs": "Popular jobs",
  "general": "General",
  "account": "Account",
  "helpcenter": "Help center",
  "appmode": "App mode",
  "applaiedjobs": "Applied jobs",
  "warningbody2": "Email or phone number already existed",
  "report": "Report",
  "abouttheapp": "About the app",
  "language": "Language",
  "follow": "Follow",
  "suggestedjobs": "Suggested jobs",
  "messages": "Messages",
  "lightmode": "Light mode",
  "aboutcompany2": "Enter a brief explanation about your company",
  "reportdescription": "Report description",
  "reporttitle": "Report title",
  "send": "Send",
  "studycase": "Study case",
  "employees": "Employees",
  "savedjobs": "Saved jobs",
  "applayforthejob": "Applay for the job",
  "uploadyourcv": "Upload your CV",
  "coverletter": "Cover letter",
  "optional": "(Optional)",
  "additionalinfo": "Additional info:",
  "editprofile": "Edit profile",
  "yourrequesthasbeensent": "Your request has been sent",
  "message": "Message",
  "popularfreelancers": "Popular freelancers",
  "verifyingcode": "Email verification",
  "receivedcode": "Please enter verification code sent to ",
  "youbirthdate": "Your birth date",
  "birthdate": "Birth date",
  "errorsendingyourrequest": "Your request has not been sent",
  "changepassword": "Change password",
  "oldpassword1": "Enter old password",
  "oldpassword2": "Old password",
  "newpassword1": "Enter new password",
  "newpassword2": "new password",
  "confirmnewpassword1": "Confirm password",
  "confirmnewpassword2": "Confirm new password",
  "resendthecode": "Resend the code after ",
  "resend": "Resend",
  "forgotyourpassword": "Forgot your password?",
  "enteremail": "Enter your email adress to send the verification code",
  "resetyourpassword": "Reset your password",
  "emailverified": "Email verified",
  "reset": "Reset",
  "enternewpassword": "Enter your new password",
  "sendingcodetoemail": "Sending verification code ",
  "passworddoesntmatch": "Password doesn't match",
  "pleaseaddanimage": "Please add an image",
  "about": "About",
  "jobs": "Jobs",
  "contact": "Contact",
  "interests": "Interests",
  "projects": "Projects",
  "products": "Products",
  "checkingcode": "Checking code",
  "wrongcode": "Wrong code",
  "empty": "Can't be empty",
  "less": "Can't be less than ",
  "more": "Can't be more than ",
  "letters": " letters",
  "pickupyourcounntry": "Pick up your country",
  "opentowork": "Open to work",
  "errorloggingin": "Error while logging in",
  "processingyourrequest": "Processing request",
  "passwordchangedsucessfully": "Password changed successfully",
  "wrongoldpassword": "Wrong old password",
  "post": "Post",
  "completeyourinfo": "Complete your information",
  "existednumber": "Phone number is already in use",
  "aboutjob2": "Explane your job",
  "jobtitle": "Job title",
  "jobtitle2": "Enter your job title",
  "requirements": "Requirements",
  "requirements2": "Add your job requirements",
  "jobtype": "Job type",
  "jobexperince": "Job experience",
  "companyinfo": "Company information",
  "shownumofemployees": "Show number of employees",
  "showaboutcompany": "Show about the company",
  "fillyourjobinfo": "Fill your job info",
  "jobadditionalinfo": "Additional information",
  "additionalinfo2": "(Optional)",
  "aboutjob1": "About job",
  "joblocation": "Job location",
  "joblocation2": "Enter the location of the job",
  "companyproducts": "Company products",
  "contactinfo": "Contact information",
  "producttitle": "Product name",
  "projecttitle": "Project name",
  "productdescription": "Product description",
  "projectdescription": "Project description",
  "projectdescription2": "Add description to your project",
  "productdescription2": "Add description to your product",
  "projectlink": "Project link",
  "gender": "Gender",
  "male": "Male",
  "female": "Female",
  "producttitle2": "Your product name",
  "savechanges": "Save changes",
  "projectimages": "Project images",
  "showmore": "Show more",
  "sendingyourreport": "Sending your report",
  "yourreporthasbeensent": "Your report has been sent",
  "projecttitle2": "Your project name",
  "link": "Link",
  "addyourlink": "Add link",
  "addimage": "Add image",
  "addyourproduct": "Add your product",
  "addyourproject": "Add your project",
  "skills": "Skills",
  "wronglogin": "Wrong email or password",
  "yourpasswordhasbeenchanged": "Your password has been changed",
  "youremailhasbeenverified": "Your email has been verified",
  "youremailisnotverified":
      "Your email isn't verified\nDo you want to verify it?",
  "emailisnotexisted": "The email is not existed",
  "checkingdata": "Checking data",
  "dateposted": "Date posted",
  "lastweek": "Last week",
  "lastmonth": "Last month",
  "addproject": "Add project",
  "addyourskill": "Add your skill",
  "addskill": "Add skill",
  "myjobs": "My jobs",
  "cantaddmorethan6images": "Cant add more than 6 images",
  "addtask": "Fill your task info",
  "tasktitle": "Task title",
  "tasklocation": "Task location",
  "tasktitle2": "Enter your task title",
  "tasklocation2": "Enter your task location",
  "abouttask1": "About task",
  "abouttask2": "Explane your task",
  "taskadditionalinfo": "Additional information",
  "taskduration": "Task duration",
  "taskduration2": "Enter your task duration",
  "days": "Days",
  "add": "Add",
  "offers": "Offers",
  "budget": "Budget",
  "job": "Job",
  "task": "Task",
  "pleasewait": "Please wait",
  "studyinfo": "Study information",
  "tasks": "Tasks",
  "mytasks": "My tasks",
  "showall": "Show all",
  "addoffer": "Add offer",
  "abouttask": "About task:",
  "addyouroffer": "Add your offer",
  "offerbudget": "Offer budget",
  "offerinfo": "Offer information",
  "excutingtime": "Excuting time",
  "value": "Value",
  "withdraw": "Withdraw:",
  "deposit": "Deposit:",
  "mybudget": "My budget",
  "min": "Min",
  "max": "Max",
  "lasttransmissions": "Last transmissions:",
  "on": "On",
  "title": "Title",
  "description": "Description",
  "images": "Images",
  "couldn'tdelete": "Couldn't delete",
  "doyoureallywanttodelete": "Do you really want to delete?",
  "errorwhilesavingdata": "Error while saving data",
  "couldn'tloadinfo": "Couldn't load information",
};
